### PR TITLE
$VERSION=0.11;_json_api improvements, get_job_details accepts optional $build_id, Invalid response includes url

### PR DESCRIPTION
**Pull request by davehorner**
* get_job_details accepts optional $build_id.
* _json_api improvements:
new params api_type allows handling of types other than json. (of course defaults to api/json)
path_ends adding elements to the end of the url.
* Invalid response includes url

### CODE REVIEW

**Comment by colinnewell** [comment]
Now that I've seen what you've done it looks like it has merit.  I'm going to sleep on that and think about it.  

I think my main concern is that the function really shouldn't be named that, I think backwards compatibility on an undocumented function starting _ isn't something to worry too much about.  We could just add in a stub with that name that calls the renamed function with the api,json args.

**Comment by davehorner** [comment]
Thanks! 

as I mentioned in the other issue:
I do agree it makes the name of that function a little of a misnomer; renaming to _api_call or something might make more sense, but again I was looking to keep backward compat.
a stub for _api_json might make sense.

Sleep well friend.
--dave

**Comment by colinnewell** [comment]
In your request you suggested that the json format might be returned on paths other than .../api/json but your modification is tied to that convention.  I think the JSON decoding ought to be a separate parameter.

**Comment by colinnewell** [comment]
The other logical thing to do to allow easy support of other plugins without a dedicated method is to make the method public and documented.

**Comment by davehorner** [comment]
I agree with all your comments I think it makes sense to have api_call (public and documented...maybe another name if you've got a better one) and a stub for _api_json so as to not break existing clients.

the other thing I'd prefer and really wanted to do is rename path_parts.  which we could do with a new method name...api_call could take {path_starts=>[]} to match the path_ends=>[] attribute.  the _api_json could still take path_parts to again keep backward compat.

I renamed the local var, but left the external as is with the current patch.
-    my $bits = $args->{path_parts} || [];
+    my $path_parts = $args->{path_parts} || [];

cheers.
--dave

**Comment by davehorner** [comment]
>the json format might be returned on paths other than .../api/json but your modification is tied to that convention. I think the JSON decoding ought to be a separate parameter.

api_type is a separate parameter, are you suggesting to take it out of args and require a arg for api_type... api/json seems to be a fine default since that is the most often used format. if not, it just returns the content as-is, no decoding.
my $api_type = $args->{api_type} || ['api', 'json'];

**Comment by colinnewell** [comment]
After thinking about this some more, if we're going to ensure backwards compatibility of the _json_api call then we should ensure it's semantics don't change.  We can add tests to ensure that.  Your current change does change the semantics because if someone has extended it they won't be expecting it to add api/json onto the end.  Normally I wouldn't care about backwards compatibility of a private method, but honestly if someone is using the library to do something I didn't explicitly support that would be a logical method to use and I'd rather not cause existing code to break.

The simplest way to ensure that that method continues to function is to not change it.  Alternatively once we have our new general purpose method we could alter the function to call it in such a way that we preserve it's current semantics.

I tweaked your alterations of the call like this to demonstrate what I meant about the json encoding, separating it.  It still needs some improvement to ensure that if someone attempts to clear the api_type field for example that it actually gets cleared, rather than defaulted back to api/json.

```perl
sub general_purpose_call
{
    my $self = shift;
    my $uri_parts = shift;
    my $args = shift;

    my $extra_params = $args->{extra_params};
    my $path_parts = $args->{path_parts} || [];
    my $api_type = $args->{api_type} || ['api', 'json'];
    my $decode_json = exists $args->{decode_json} ? $args->{decode_json} : 1;
    my $path_ends = $args->{path_ends} || [];

    my $uri = URI->new($self->base_url);
    $uri->path_segments(@$path_parts, @$uri_parts, @$path_ends, @$api_type);
    $uri->query_form($extra_params) if $extra_params;

    $self->_client->GET($uri->path_query);
    die 'Invalid response: '.$uri->path_query unless $self->_client->responseCode eq '200';
    # NOTE: my server returns UTF8, if this turns out to be a broken
    # assumption read the Content-Type header.
    my $response = $self->_client->responseContent();
    if($decode_json)
    {
        $response = JSON->new->utf8->decode($response);
    }
    return $response;
}
```

**Comment by davehorner** [comment]
>Your current change does change the semantics because if someone has extended it they won't be expecting it to add api/json onto the end.

I understand that my changes are changing the semantics in that the api_type is being added always and that we remove api/json from the uri_parts to make that work...which means all callers would need to know about this convention change.  (_ private method changes would be ok as long as all the api calls internal make the change, but I guess we can be cautious to support outside callers) callers which do not remove the api/json from the uri_parts might get two api/json/api/json as a result; which we do not want.  But leaving api/json in the uri_parts, does not give the caller the freedom to add elements before api/json...

I like changing the _json_api call so that those calls that were making use of it, can be extended  before and after the static elements...and also provide support for other data types (xml).  I would prefer extending view_status() via arguments; making the existing functions work better instead of pushing people to re-implement the same calls via the general_purpose_call to get the added flexibility.  The api then amounts to always using the general_purpose_call.

I guess I think it would be better to not modify the url at all by default and not have decoding tied to the url.
The api_type would not be used in the path_segments at all and could be used as the decode_json variable you suggest, 1 or 0, or defaulting to 'json' and if ne to 'json' just returning  $self->_client->responseContent();  

The calls to _json_api instead of dropping 'api', 'json' all together
from:
return $self->_json_api(['view', $view, 'api', 'json'], @_);
to:
return $self->_json_api(['view', $view], @_);

it would be nice if the internal calls could make use of the path_ends for passing the ['api','json'] part so that the caller can override this with something else.
my(%optional_args)=@_;
$optional_args{path_ends}=>['api','json'] !exists $optional_args{path_ends};
return $self->_json_api(['view', $view], $optional_args);

I didn't test the above code but something close to this might work for the internal calls to _json_api.
I just would like to see path_ends added to all the existing named api functions so that they all can operate similarly and so that  view_status()/et. al doesn't get re-implemented using the general function.

Ultimately it doesn't matter all that much - if we change _json_api or not; I just want to see the new general api added soon if at all possible so that I may start using it to implement current needs.

Thanks Colin,
--dave

**Comment by colinnewell** [comment]
I'm not completely against extending the existing public calls, I just don't want to break existing code.  That either means ensuring that the _json_api call allows some degree of extension without breaking it's existing semantics, or we create a new method, and route everything through that.  That has the upside of not breaking everything, although it does leave the weird situation of having an undocumented method in the code that is not technically used by anything in the code.

As you say however I agree that the general purpose method is a higher priority.  I've created issue #14 to discuss that.  We just need to agree some kind of semantics for that method.  I'm going to assume that it's got a clean slate so we can remove some of the clunkiness of the private method.  Refactoring the private method afterwards isn't necessarily out of the question however despite that.

**Comment by colinnewell** [comment]
I'm closing this pull request as we have captured the requirements in issues #14 and #15, and #14 is delivered.

**Pull request closed without merging**
